# This is base config

[base]
    debug_mode="debug"
    time_location="Asia/Guangzhou"

[http]
    addr =":8881"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 10                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度
    allow_ip = [                        # 白名单ip列表
        "127.0.0.1",
        "192.168.1.1"
    ]

