[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:root@tcp(localhost:3306)/test?charset=utf8&parseTime=true"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100
